[package]
name = "polygl-lir"
description = "Low-level intermediate representation for PolyGL"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
polygl-builtins = { path = "../polygl-builtins" }
polygl-hir = { path = "../polygl-hir" }
polygl-span = { path = "../polygl-span" }
polygl-types = { path = "../polygl-types" }

[lints]
workspace = true
