[package]
name = "polygl-adapter-perl"
description = "Perl language adapter for PolyGL"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
polygl-adapter-api = { path = "../polygl-adapter-api", version = "=0.1.0" }
polygl-adapter-treesitter-util = { path = "../polygl-adapter-treesitter-util", version = "=0.1.0" }
polygl-hir = { path = "../polygl-hir", version = "=0.1.0" }
polygl-span = { path = "../polygl-span", version = "=0.1.0" }
tree-sitter = "=0.26.12"
ts-parser-perl = "=1.2.1"

[dev-dependencies]
polygl-builtins = { path = "../polygl-builtins", version = "=0.1.0" }
polygl-types = { path = "../polygl-types", version = "=0.1.0" }

[lints]
workspace = true
