[package]
name = "polygl-hir"
description = "High-level intermediate representation for PolyGL"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
polygl-span = { path = "../polygl-span", version = "=0.1.0" }

[lints]
workspace = true
