[package]
name = "polygl-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.4.13"
polygl-adapter-api = { path = "../crates/polygl-adapter-api", version = "=0.1.0" }
polygl-adapter-perl = { path = "../crates/polygl-adapter-perl", version = "=0.1.0" }
polygl-adapter-php = { path = "../crates/polygl-adapter-php", version = "=0.1.0" }
polygl-adapter-ruby = { path = "../crates/polygl-adapter-ruby", version = "=0.1.0" }
polygl-backend-glsl = { path = "../crates/polygl-backend-glsl", version = "=0.1.0" }
polygl-backend-js = { path = "../crates/polygl-backend-js", version = "=0.1.0" }
polygl-core = { path = "../crates/polygl-core", version = "=0.1.0" }
polygl-lir = { path = "../crates/polygl-lir", version = "=0.1.0" }
polygl-span = { path = "../crates/polygl-span", version = "=0.1.0" }
polygl-types = { path = "../crates/polygl-types", version = "=0.1.0" }

[[bin]]
name = "frontend"
path = "fuzz_targets/frontend.rs"
test = false
doc = false
bench = false

[[bin]]
name = "pipeline"
path = "fuzz_targets/pipeline.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
