[package]
name = "polygl-adapter-api"
description = "Public language adapter API for PolyGL"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
polygl-hir = { path = "../polygl-hir", version = "=0.1.0" }
polygl-span = { path = "../polygl-span", version = "=0.1.0" }

[lints]
workspace = true
