[package]
name = "polygl-backend-js"
description = "JavaScript backend for PolyGL"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64 = "=0.23.1"
polygl-lir = { path = "../polygl-lir", version = "=0.1.0" }
polygl-span = { path = "../polygl-span", version = "=0.1.0" }
polygl-types = { path = "../polygl-types", version = "=0.1.0" }
serde_json = "=1.0.151"

[dev-dependencies]
polygl-builtins = { path = "../polygl-builtins", version = "=0.1.0" }

[lints]
workspace = true
