[package]
name = "polygl-adapter-ruby"
description = "Ruby language adapter for PolyGL"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
polygl-adapter-api = { path = "../polygl-adapter-api", version = "=0.1.0" }
polygl-hir = { path = "../polygl-hir", version = "=0.1.0" }
polygl-span = { path = "../polygl-span", version = "=0.1.0" }
ruby-prism = "=1.9.0"

[dev-dependencies]
polygl-builtins = { path = "../polygl-builtins", version = "=0.1.0" }

[lints]
workspace = true
