[package]
name = "polygl-core"
description = "Compiler pipeline orchestration for PolyGL"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
polygl-builtins = { path = "../polygl-builtins", version = "=0.1.0" }

[lints]
workspace = true
