use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::Path;

use polygl_core::{Builtin, BuiltinTable, DefaultValue, Domain, Parameter};

use crate::workspace_root;

pub(crate) fn generate_runtime(check: bool) -> io::Result<()> {
    BuiltinTable::validate().map_err(io::Error::other)?;
    let outputs = [
        ("runtime/src/generated/ops.ts", render_typescript()),
        ("docs/api.md", render_api_docs()),
    ];

    for (relative_path, contents) in outputs {
        let path = workspace_root().join(relative_path);
        if check {
            let current = fs::read_to_string(&path)?;
            if current != contents {
                return Err(io::Error::other(format!(
                    "{} is stale; run `cargo xtask gen-runtime`",
                    path.display()
                )));
            }
        } else {
            write_generated_file(&path, &contents)?;
        }
    }
    Ok(())
}

fn write_generated_file(path: &Path, contents: &str) -> io::Result<()> {
    let Some(parent) = path.parent() else {
        return Err(io::Error::other("generated output has no parent"));
    };
    fs::create_dir_all(parent)?;
    fs::write(path, contents)
}

fn render_typescript() -> String {
    let mut output =
        "// @generated by `cargo xtask gen-runtime`; do not edit manually.\n\n".to_owned();
    output.push_str(
        "export type RuntimeDomain = \"host\" | \"gpu\" | \"both\";\n\
         export type RuntimeValueType = \"void\" | \"int\" | \"float\" | \"bool\" | \"str\";\n\n\
         export interface RuntimeParameterSpec {\n\
         \u{20} readonly name: string;\n\
         \u{20} readonly type: RuntimeValueType;\n\
         \u{20} readonly default?: number | boolean;\n\
         }\n\n",
    );
    output.push_str("export const runtimeOps = Object.freeze({\n");
    for builtin in BuiltinTable::all() {
        writeln!(
            output,
            "  {}: \"{}\",",
            builtin.name,
            builtin.runtime_op.as_str()
        )
        .unwrap();
    }
    output.push_str(
        "} as const);\n\
         export type BuiltinName = keyof typeof runtimeOps;\n\
         export type RuntimeOp = (typeof runtimeOps)[BuiltinName];\n\n\
         export const runtimeSignatures = Object.freeze({\n",
    );
    for builtin in BuiltinTable::all() {
        write!(
            output,
            "  {}: {{ domain: \"{}\", params: [",
            builtin.name,
            typescript_domain(builtin.domain)
        )
        .unwrap();
        for (index, param) in builtin.signature.params.iter().enumerate() {
            if index > 0 {
                output.push_str(", ");
            }
            write!(
                output,
                "{{ name: \"{}\", type: \"{}\"",
                param.name,
                param.ty.as_str()
            )
            .unwrap();
            if let Some(default) = param.default {
                write!(output, ", default: {}", default_literal(default)).unwrap();
            }
            output.push_str(" }");
        }
        writeln!(
            output,
            "], result: \"{}\" }},",
            builtin.signature.result.as_str()
        )
        .unwrap();
    }
    output.push_str("} as const);\n");
    output
}

fn render_api_docs() -> String {
    let mut output = "\
<!-- @generated by `cargo xtask gen-runtime`; do not edit manually. -->

# Common API

Colors use normalized floating-point channels in the range 0–1. Angles are in
radians. Coordinates are measured in canvas pixels. `random` uses the
runtime seed, while GPU code must use deterministic shader inputs instead.

| Tier | Function | Result | Domain | RuntimeOp |
|---|---|---|---|---|
"
    .to_owned();
    for builtin in BuiltinTable::all() {
        writeln!(
            output,
            "| {} | `{}` | `{}` | {} | `{}` |",
            builtin.tier.as_str(),
            markdown_signature(builtin),
            builtin.signature.result.as_str(),
            builtin.domain.as_str(),
            builtin.runtime_op.as_str()
        )
        .unwrap();
    }
    output.push_str(
        "\n`time()` maps to the automatic `u_time` uniform in GPU code. All other\n\
         Tier 1 drawing, input, matrix, and canvas operations are Host-only.\n",
    );
    output
}

fn markdown_signature(builtin: &Builtin) -> String {
    let params = builtin
        .signature
        .params
        .iter()
        .map(markdown_parameter)
        .collect::<Vec<_>>()
        .join(", ");
    format!("{}({params})", builtin.name)
}

fn markdown_parameter(param: &Parameter) -> String {
    match param.default {
        Some(default) => format!("{}: {} = {default}", param.name, param.ty.as_str()),
        None => format!("{}: {}", param.name, param.ty.as_str()),
    }
}

fn default_literal(default: DefaultValue) -> String {
    default.to_string()
}

const fn typescript_domain(domain: Domain) -> &'static str {
    match domain {
        Domain::Host => "host",
        Domain::Gpu => "gpu",
        Domain::Both => "both",
    }
}

#[cfg(test)]
mod tests {
    use super::{render_api_docs, render_typescript};

    #[test]
    fn generated_outputs_include_domain_and_defaults() {
        let typescript = render_typescript();
        assert!(typescript.contains("time: { domain: \"both\""));
        assert!(typescript.contains("default: 1"));
        let docs = render_api_docs();
        assert!(docs.contains("`fill(r: float, g: float, b: float, a: float = 1)`"));
        assert!(docs.contains("| Tier 1 | `random("));
    }
}
